import "./globals.css";
import { Urbanist } from 'next/font/google';

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400','500', '600', '700', '800', '900'], // font weights
  variable: '--font-urbanist',   // linked to css variable.
});

export const metadata = {
  title: "Secutech Arabia",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // S icon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={urbanist.variable} >
        {children}
      </body>
    </html>
  );
}
